version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: coderacer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # В реальном Swarm конфиги/скрипты лучше передавать через configs или secrets
      # Для простоты монтируем, но это требует наличия файла на ноде
    networks:
      - coderacer-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  backend:
    image: coderacer-backend:latest
    environment:
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: coderacer
      DB_USER: postgres
      DB_PASSWORD: postgres
      STATISTICS_SERVICE_URL: http://statistics-service:3002
      NOTIFICATION_SERVICE_URL: http://notification-service:3003
    networks:
      - coderacer-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  statistics-service:
    image: coderacer-statistics:latest
    environment:
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: coderacer
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - coderacer-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s

  notification-service:
    image: coderacer-notifications:latest
    environment:
      PORT: 3003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: coderacer
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - coderacer-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s

  frontend:
    image: coderacer-frontend:latest
    networks:
      - coderacer-network
    deploy:
      replicas: 2

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    # В Swarm конфиг nginx лучше передавать через docker config
    # configs:
    #   - source: nginx_config
    #     target: /etc/nginx/conf.d/default.conf
    # Для учебных целей оставим простой образ, но Nginx требует конфига. 
    # Самый простой способ в Swarm без внешних волюмов - создать свой образ Nginx с конфигом.
    # Либо использовать configs. Давайте используем configs, это правильно для Swarm.
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - coderacer-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  coderacer-network:
    driver: overlay

volumes:
  postgres_data:

configs:
  nginx_conf:
    file: ./nginx/nginx.conf

